# Generated by Django 5.2.4 on 2025-07-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexo', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
