# Generated by Django 5.2.4 on 2025-07-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
