# Generated by Django 4.2.23 on 2025-07-15 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_vision', '0002_medicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('umidade', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
